package org.imprime.ai.api.model.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.imprime.ai.api.model.converter.CodeAttributeConverter;

@Getter
@RequiredArgsConstructor
public enum MessageCd implements CodeAttribute {

    //region System
    INTERNAL_SERVER_ERROR("SYS_500"),
    GENERIC_404("SYS_404"),
    //endregion

    //region Auth
    UNAUTHORIZED("AUTH_401"),
    //endregion

    //region User
    MISSING_USER_FIRST_NAME("USR_001"),
    USER_FIRST_NAME_INVALID_LENGTH("USR_002"),
    INVALID_USER_FIRST_NAME("USR_003"),

    MISSING_USER_LAST_NAME("USR_004"),
    USER_LAST_NAME_INVALID_LENGTH("USR_005"),
    INVALID_USER_LAST_NAME("USR_006"),

    MISSING_USER_EMAIL("USR_007"),
    INVALID_USER_EMAIL("USR_008"),

    MISSING_USER_PASSWORD("USR_009"),
    INVALID_USER_PASSWORD("USR_010"),

    MISSING_USER_CONFIRM_PASSWORD("USR_011"),
    USER_PASSWORD_MISMATCH("USR_012"),

    MISSING_USER_DOCUMENT_TYPE("USR_013"),
    INVALID_DOCUMENT_TYPE("USR_014"),

    MISSING_USER_DOCUMENT("USR_015"),

    MISSING_USER_PHONE_NUMBER("USR_016"),
    INVALID_USER_PHONE_NUMBER("USR_017"),

    MISSING_USER_ADDRESS("USR_018"),
    MISSING_USER_COMPANY("USR_019"),

    MISSING_USER_IS_MAKER("USR_020"),
    USER_EMAIL_ALREADY_REGISTERED("USR_021"),
    USER_DOCUMENT_ALREADY_REGISTERED("USR_022"),
    //endregion

    //region Document
    INVALID_CPF("DOC_001"),
    INVALID_RG("DOC_002"),
    INVALID_CNPJ("DOC_003"),
    //endregion

    //region Address
    MISSING_ADDRESS_ZIP_CODE("ADR_001"),
    INVALID_ADDRESS_ZIP_CODE("ADR_002"),

    MISSING_ADDRESS_NEIGHBORHOOD("ADR_003"),
    INVALID_ADDRESS_NEIGHBORHOOD("ADR_004"),
    INVALID_ADDRESS_NEIGHBORHOOD_LENGTH("ADR_005"),

    MISSING_ADDRESS_CITY("ADR_006"),
    INVALID_ADDRESS_CITY("ADR_007"),
    INVALID_ADDRESS_CITY_LENGTH("ADR_008"),

    MISSING_ADDRESS_STATE("ADR_009"),
    INVALID_ADDRESS_STATE("ADR_010"),

    MISSING_ADDRESS_COUNTRY("ADR_011"),
    INVALID_ADDRESS_COUNTRY("ADR_012"),
    INVALID_ADDRESS_COUNTRY_LENGTH("ADR_013"),

    MISSING_ADDRESS_LINE_1("ADR_014"),
    INVALID_ADDRESS_LINE_1("ADR_015"),
    INVALID_ADDRESS_LINE_1_LENGTH("ADR_016"),

    INVALID_ADDRESS_LINE_2("ADR_017"),
    INVALID_ADDRESS_LINE_2_LENGTH("ADR_018"),
    //endregion

    //region Company
    MISSING_COMPANY_NAME("COM_001"),
    INVALID_COMPANY_NAME("COM_002"),
    INVALID_COMPANY_NAME_LENGTH("COM_003"),

    MISSING_COMPANY_DOCUMENT_TYPE("COM_004"),
    INVALID_COMPANY_DOCUMENT_TYPE("COM_005"),

    MISSING_COMPANY_DOCUMENT("COM_006"),

    MISSING_COMPANY_ADDRESS("COM_007"),
    COMPANY_NAME_ALREADY_REGISTERED("COM_008"),
    COMPANY_DOCUMENT_ALREADY_REGISTERED("COM_009"),

    //endregion

    //region Phone
    INVALID_PHONE_FORMAT("PHO_001"),
    //endregion
    ;

    private final String code;

    public static class Converter extends CodeAttributeConverter<MessageCd> {
        public Converter() {
            super(MessageCd.class);
        }
    }
}