spring:
  application:
    name: Imprime Ai

logging:
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} userId[%X{user-id}] transactionId[%X{transaction-id}] %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'

imprime:
  ai:
    api:
      default-language: en_us

oci:
  object-storage:
    namespace: ${OCI_OBJECT_STORAGE_NAMESPACE}
    bucket-name: ${OCI_OBJECT_STORAGE_BUCKET}
    config-file: ${OCI_CONFIG_FILE:./secret/oci.cfg}
    profile: ${OCI_CONFIG_PROFILE:DEFAULT}
    region-id: ${OCI_REGION_ID:sa-saopaulo-1}