ALTER TABLE MESSAGE_LKUP
    DROP CONSTRAINT UQ_MESSAGE_LKUP_CODE_LANG;

ALTER TABLE MESSAGE_LKUP
    DROP COLUMN LANGUAGE_CODE;

ALTER TABLE MESSAGE_LKUP ADD CONSTRAINT UQ_MESSAGE_LKUP_CODE UNIQUE(CODE);