CREATE TABLE orders
(
    order_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id            NUMBER    NOT NULL,
    vendor_id           NUMBER    NOT NULL,
    file_asset_id       NUMBER    NOT NULL,
    from_address_id     NUMBER    NOT NULL,
    to_address_id       NUMBER    NOT NULL,
    pricing_strategy_id NUMBER,
    status_id           NUMBER    NOT NULL,
    create_dt           TIMESTAMP WITH TIME ZONE
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    create_user         VARCHAR2(100),
    update_dt           TIMESTAMP WITH TIME ZONE,
    update_user         VARCHAR2(100),


    CONSTRAINT fk_order_buyer
        FOREIGN KEY (buyer_id)
            REFERENCES users(user_id),

    CONSTRAINT fk_order_vendor
        FOREIGN KEY (vendor_id)
            REFERENCES users(user_id),

    CONSTRAINT fk_order_model
        FOREIGN KEY (file_asset_id)
            REFERENCES file_asset(file_asset_id),

    CONSTRAINT fk_order_from_address
        FOREIGN KEY (from_address_id)
            REFERENCES address(address_id),

    CONSTRAINT fk_order_to_address
        FOREIGN KEY (to_address_id)
            REFERENCES address(address_id),

    CONSTRAINT fk_order_pricing_strategy
        FOREIGN KEY (pricing_strategy_id)
            REFERENCES pricing_strategy(pricing_strategy_id),

    CONSTRAINT fk_order_status
        FOREIGN KEY (status_id)
            REFERENCES order_status_lkup(status_id)
);

CREATE INDEX idx_orders_buyer
    ON orders(buyer_id);

CREATE INDEX idx_orders_vendor
    ON orders(vendor_id);

CREATE INDEX idx_orders_model
    ON orders(file_asset_id);

CREATE INDEX idx_orders_pricing_strategy
    ON orders(pricing_strategy_id);

CREATE INDEX idx_orders_status_id
    ON orders(status_id);