CREATE TABLE order_status
(
    order_status_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        NUMBER        NOT NULL,
    status_id       NUMBER        NOT NULL,
    status_date     TIMESTAMP WITH TIME ZONE
        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status          VARCHAR2(5),
    create_dt       TIMESTAMP WITH TIME ZONE
        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    create_user     VARCHAR2(100),
    update_dt       TIMESTAMP WITH TIME ZONE,
    update_user     VARCHAR2(100),

    CONSTRAINT fk_order_status_order
        FOREIGN KEY (order_id)
            REFERENCES orders (order_id)
                ON DELETE CASCADE,

    CONSTRAINT fk_order_status_lkup
        FOREIGN KEY (status_id)
            REFERENCES order_status_lkup (status_id)
);