CREATE TABLE auth_token
(
    auth_token_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER                              NOT NULL,
    token_hash  VARCHAR2(64)                        NOT NULL UNIQUE,
    type        VARCHAR2(5)                         NOT NULL,
    revoked     NUMBER(1) DEFAULT 0                 NOT NULL
        CHECK (revoked IN (0, 1)),
    expires_at  TIMESTAMP WITH TIME ZONE            NOT NULL,
    status      VARCHAR2(5),
    create_dt   TIMESTAMP WITH TIME ZONE
                          DEFAULT CURRENT_TIMESTAMP NOT NULL,
    create_user VARCHAR2(100),
    update_dt   TIMESTAMP WITH TIME ZONE,
    update_user VARCHAR2(100),

    CONSTRAINT fk_tokens_user
        FOREIGN KEY (user_id)
            REFERENCES users (user_id)
                ON DELETE CASCADE
);

CREATE INDEX idx_tokens_user_id
    ON auth_token (user_id);