CREATE TABLE users
(
    user_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    first_name         VARCHAR2(100) NOT NULL,
    last_name          VARCHAR2(100) NOT NULL,
    document           VARCHAR2(20)  NOT NULL UNIQUE,
    email              VARCHAR2(255) NOT NULL UNIQUE,
    password_hash      VARCHAR2(255) NOT NULL,
    phone_country      VARCHAR2(5)   NOT NULL,
    phone_number       VARCHAR2(20)  NOT NULL,
    primary_address_id NUMBER,
    status             VARCHAR2(5),
    create_dt          TIMESTAMP WITH TIME ZONE
        DEFAULT CURRENT_TIMESTAMP    NOT NULL,
    create_user        VARCHAR2(100),
    update_dt          TIMESTAMP WITH TIME ZONE,
    update_user        VARCHAR2(100)
);

COMMENT ON TABLE users IS 'Platform users (buyers and vendors)';