INSERT INTO message_lkup (CODE, LANGUAGE_CODE, TEXT, TYPE, GUID, STATUS, CREATE_DT, CREATE_USER, UPDATE_DT, UPDATE_USER)
VALUES
    ('SYS_500', 'es-ES', 'Error interno del servidor', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('AUTH_401', 'es-ES', 'No autorizado', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('SYS_404', 'es-ES', 'Página no encontrada', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_001', 'es-ES', 'El nombre es obligatorio', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_002', 'es-ES', 'El nombre debe tener entre 3 y 100 caracteres', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_003', 'es-ES', 'El nombre contiene caracteres no válidos', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_004', 'es-ES', 'El apellido es obligatorio', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_005', 'es-ES', 'El apellido debe tener entre 3 y 100 caracteres', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_006', 'es-ES', 'El apellido contiene caracteres no válidos', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_007', 'es-ES', 'El correo electrónico es obligatorio', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_008', 'es-ES', 'El correo electrónico no es válido', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_009', 'es-ES', 'La contraseña es obligatoria', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_010', 'es-ES', 'La contraseña debe contener al menos 1 letra mayúscula, 1 letra minúscula, 1 número, 1 carácter especial y tener entre 8 y 32 caracteres', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_011', 'es-ES', 'La confirmación de la contraseña es obligatoria', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_012', 'es-ES', 'Las contraseñas no coinciden', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_013', 'es-ES', 'El tipo de documento es obligatorio', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_014', 'es-ES', 'El tipo de documento debe ser uno de los siguientes: CPF, RG', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_015', 'es-ES', 'El documento es obligatorio', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_016', 'es-ES', 'El número de teléfono es obligatorio', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_017', 'es-ES', 'El número de teléfono no es válido', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_018', 'es-ES', 'La dirección es obligatoria', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_019', 'es-ES', 'La información de la empresa es obligatoria', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('USR_020', 'es-ES', 'El indicador de fabricante es obligatorio', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('DOC_001', 'es-ES', 'El CPF no es válido', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('DOC_002', 'es-ES', 'El RG no es válido', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('DOC_003', 'es-ES', 'El CNPJ no es válido', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_001', 'es-ES', 'El código postal es obligatorio', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_002', 'es-ES', 'El código postal no es válido', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_003', 'es-ES', 'El barrio es obligatorio', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_004', 'es-ES', 'El barrio no es válido', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_005', 'es-ES', 'El barrio debe tener entre 2 y 100 caracteres', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_006', 'es-ES', 'La ciudad es obligatoria', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_007', 'es-ES', 'La ciudad no es válida', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_008', 'es-ES', 'La ciudad debe tener entre 2 y 100 caracteres', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_009', 'es-ES', 'El estado es obligatorio', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_010', 'es-ES', 'El estado no es válido', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_011', 'es-ES', 'El país es obligatorio', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_012', 'es-ES', 'El país no es válido', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_013', 'es-ES', 'El país debe tener entre 2 y 100 caracteres', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_014', 'es-ES', 'La dirección línea 1 es obligatoria', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_015', 'es-ES', 'La dirección línea 1 no es válida', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_016', 'es-ES', 'La dirección línea 1 debe tener entre 5 y 255 caracteres', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_017', 'es-ES', 'La dirección línea 2 no es válida', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('ADR_018', 'es-ES', 'La dirección línea 2 no debe superar los 255 caracteres', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('COM_001', 'es-ES', 'El nombre de la empresa es obligatorio', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('COM_002', 'es-ES', 'El nombre de la empresa no es válido', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('COM_003', 'es-ES', 'El nombre de la empresa debe tener entre 2 y 100 caracteres', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('COM_004', 'es-ES', 'El tipo de documento de la empresa es obligatorio', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('COM_005', 'es-ES', 'El tipo de documento de la empresa debe ser uno de los siguientes: CPF, CNPJ', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('COM_006', 'es-ES', 'El documento de la empresa es obligatorio', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre'),
    ('COM_007', 'es-ES', 'La dirección de la empresa es obligatoria', 'E', uuid(), 'A', CURRENT_TIMESTAMP, 'Andre', CURRENT_TIMESTAMP, 'Andre');