CREATE TABLE address
(
    address_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER                              NOT NULL,
    country         VARCHAR2(100)                       NOT NULL,
    state           VARCHAR2(100),
    city            VARCHAR2(100),
    zip_code        VARCHAR2(20),
    address_line_1  VARCHAR2(255)                       NOT NULL,
    address_line_2  VARCHAR2(255),
    default_address NUMBER(1) DEFAULT 0                 NOT NULL
        CHECK (default_address IN (0, 1)),
    status          VARCHAR2(5),
    create_dt       TIMESTAMP WITH TIME ZONE
                              DEFAULT CURRENT_TIMESTAMP NOT NULL,
    create_user     VARCHAR2(100),
    update_dt       TIMESTAMP WITH TIME ZONE,
    update_user     VARCHAR2(100),

    CONSTRAINT fk_address_user
        FOREIGN KEY (user_id)
            REFERENCES users (user_id)
                ON DELETE CASCADE
);

CREATE INDEX idx_address_user_id
    ON address (user_id);

ALTER TABLE users
    ADD CONSTRAINT fk_users_primary_address
        FOREIGN KEY (primary_address_id)
            REFERENCES address (address_id);