CREATE TABLE file_asset
(
    file_asset_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER          NOT NULL,
    image_url     VARCHAR2(1000),
    name          VARCHAR2(255)   NOT NULL,
    status        VARCHAR2(5),
    create_dt     TIMESTAMP WITH TIME ZONE
        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    create_user   VARCHAR2(100),
    update_dt     TIMESTAMP WITH TIME ZONE,
    update_user   VARCHAR2(100),

    CONSTRAINT fk_file_asset_user
        FOREIGN KEY (user_id)
            REFERENCES users (user_id)
                ON DELETE CASCADE
);

CREATE INDEX idx_file_asset_user_id
    ON file_asset (user_id);