CREATE TABLE asset
(
    asset_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       NUMBER        NOT NULL,
    model            VARCHAR2(255) NOT NULL,
    make             VARCHAR2(255) NOT NULL,
    manufacture_year NUMBER(4)     NOT NULL,
    tray_width       NUMBER(10, 2),
    tray_depth       NUMBER(10, 2),
    status           VARCHAR2(5),
    create_dt        TIMESTAMP WITH TIME ZONE
        DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    create_user      VARCHAR2(100),
    update_dt        TIMESTAMP WITH TIME ZONE,
    update_user      VARCHAR2(100),

    CONSTRAINT fk_asset_company
        FOREIGN KEY (company_id)
            REFERENCES company (company_id)
                ON DELETE CASCADE
);

CREATE INDEX idx_asset_company_id
    ON asset (company_id);