CREATE TABLE filament
(
    filament_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER          NOT NULL,
    asset_id      NUMBER,
    stock         NUMBER(10, 2)   NOT NULL,
    filament_type VARCHAR2(100)   NOT NULL,
    description   CLOB,
    status        VARCHAR2(5),
    create_dt     TIMESTAMP WITH TIME ZONE
        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    create_user   VARCHAR2(100),
    update_dt     TIMESTAMP WITH TIME ZONE,
    update_user   VARCHAR2(100),

    CONSTRAINT fk_filament_user
        FOREIGN KEY (user_id)
            REFERENCES users (user_id)
                ON DELETE CASCADE,

    CONSTRAINT fk_filament_asset
        FOREIGN KEY (asset_id)
            REFERENCES asset (asset_id)
                ON DELETE SET NULL
);

CREATE INDEX idx_filament_user_id
    ON filament (user_id);

CREATE INDEX idx_filament_asset_id
    ON filament (asset_id);