CREATE TABLE company
(
    company_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    NUMBER            NOT NULL,
    name        VARCHAR2(100) UNIQUE,
    cnpj        VARCHAR2(20) UNIQUE,
    address_id  NUMBER,
    status      VARCHAR2(5),
    create_dt   TIMESTAMP WITH TIME ZONE
        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    create_user VARCHAR2(100),
    update_dt   TIMESTAMP WITH TIME ZONE,
    update_user VARCHAR2(100),

    CONSTRAINT fk_vendor_user
        FOREIGN KEY (owner_id)
            REFERENCES users (user_id)
                ON DELETE CASCADE,

    CONSTRAINT fk_vendor_address
        FOREIGN KEY (address_id)
            REFERENCES address (address_id)
);

ALTER TABLE users
    ADD company_id NUMBER;

CREATE INDEX idx_user_company_id
    ON users (company_id);

ALTER TABLE users
    ADD CONSTRAINT fk_users_company_id
        FOREIGN KEY (company_id)
            REFERENCES company (company_id);