CREATE TABLE pricing_strategy
(
    pricing_strategy_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id           NUMBER                              NOT NULL,
    name                VARCHAR2(255)                       NOT NULL,
    is_active           NUMBER(1) DEFAULT 1                 NOT NULL
        CHECK (is_active IN (0, 1)),
    status              VARCHAR2(5),
    create_dt           TIMESTAMP WITH TIME ZONE
                                  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    create_user         VARCHAR2(100),
    update_dt           TIMESTAMP WITH TIME ZONE,
    update_user         VARCHAR2(100),

    CONSTRAINT fk_pricing_strategy_vendor
        FOREIGN KEY (vendor_id)
            REFERENCES users (user_id)
                ON DELETE CASCADE
);

CREATE INDEX idx_pricing_strategy_vendor_id
    ON pricing_strategy (vendor_id);

COMMENT ON TABLE pricing_strategy
    IS 'Grouping of pricing rules per vendor';