CREATE TABLE pricing_rule
(
    pricing_rule_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pricing_strategy_id  NUMBER        NOT NULL,
    implementation_class VARCHAR2(255) NOT NULL,
    configs              CLOB
        CONSTRAINT chk_pricing_rule_configs_json
            CHECK (configs IS JSON),
    execution_order      NUMBER        NOT NULL,
    status               VARCHAR2(5),
    create_dt            TIMESTAMP WITH TIME ZONE
        DEFAULT CURRENT_TIMESTAMP      NOT NULL,
    create_user          VARCHAR2(100),
    update_dt            TIMESTAMP WITH TIME ZONE,
    update_user          VARCHAR2(100),

    CONSTRAINT uq_pricing_rule_execution_order
        UNIQUE (pricing_strategy_id, execution_order),

    CONSTRAINT fk_pricing_rule_strategy
        FOREIGN KEY (pricing_strategy_id)
            REFERENCES pricing_strategy (pricing_strategy_id)
                ON DELETE CASCADE
);

CREATE INDEX idx_pricing_rule_strategy_id
    ON pricing_rule (pricing_strategy_id);

COMMENT ON TABLE pricing_rule
    IS 'Composable pricing rules inside a strategy';